### ISSUE TITLE
sizeLimit and chunking enabled

### ISSUE THREAD

**Issue by am05mhz** [FineUploader/php-traditional-server#1]
there is a problem in limiting upload size when chunking is enabled, as the size limit is compared to each chunk, which result in upload always allowed when chunk size is smaller than size limit.

    <?php
    $uploader = new UploadHandler();

    // Specify the list of valid extensions, ex. array("jpeg", "xml", "bmp")
    $uploader->allowedExtensions = array(); // all files types allowed by default

    // Specify max file size in bytes.
    $uploader->sizeLimit = 1024 * 1024; // limit at 1 MiB

    // Specify the input name set in the javascript.
    $uploader->inputName = "qqfile"; // matches Fine Uploader's default inputName value by default

    // If you want to use the chunking/resume feature, specify the folder to temporarily save parts.
    $uploader->chunksFolder = "chunks";

    $method = $_SERVER["REQUEST_METHOD"];
    if ($method == "POST") {
        header("Content-Type: text/plain");

        // Assumes you have a chunking.success.endpoint set to point here with a query parameter of "done".
        // For example: /myserver/handlers/endpoint.php?done
        if (isset($_GET["done"])) {
            $result = $uploader->combineChunks("files");
        }
        // Handles upload requests
        else {
            // Call handleUpload() with the name of the folder, relative to PHP's getcwd()
            $result = $uploader->handleUpload("files");

            // To return a name used for uploaded file you can use the following line.
            $result["uploadName"] = $uploader->getUploadName();
        }

        echo json_encode($result);
    }
    // for delete file requests
    else if ($method == "DELETE") {
        $result = $uploader->handleDelete("files");
        echo json_encode($result);
    }
    else {
        header("HTTP/1.0 405 Method Not Allowed");
    }
    ?>

js side:

    uploader = new qq.FineUploader({
    			element: document.getElementById('uploader'),
    			template: 'uploader-template',
    			chunking: {
    				enabled: true,
    				partSize: 200*1024, //chunk at 200kb
    				success: {
    					endpoint: done_endpoint
    				}
    			},
    			request: {
    				endpoint: request_endpoint
    			},
    }

**Comment by rnicholus** [comment]
You have posted the code for [endpoint.php](https://github.com/FineUploader/php-traditional-server/blob/1.0.0/endpoint.php), but issue actually exists in [handler.php](https://github.com/FineUploader/php-traditional-server/blob/1.0.0/handler.php).

I haven't attempted to reproduce, but I do see what appears to be an issue [in the PHP code](https://github.com/FineUploader/php-traditional-server/blob/1.0.0/handler.php#L130). I think the easiest fix is to first look at the request payload. If a `qqtotalfilesize` parameter exists, then that should be used to verify that the file is not too large, otherwise, the actual size of the file in the request should be used. Additionally, before combining all chunks, the total size of all chunks should be checked to ensure it does not exceed the mandated maximum file size. 

If you are able to issue a pull request with this fix, that may be fastest. Otherwise, I will look into fixing this as time allows over the next week or so.

**Comment by am05mhz** [comment]
Hi @rnicholus,

Thanks for your suggestion, I'll try that.

**Comment by am05mhz** [comment]
Hi @rnicholus,

It does fix the problem, thanks

for your info, returning `{"error":"reason"}` to `chunking.success.endpoint` does not trigger `onError` in the client side, but checking the `qqtotalfilesize` in `handleUpload` solve the problem.

    // Assumes you have a chunking.success.endpoint set to point here with a query parameter of "done".
    // For example: /myserver/handlers/endpoint.php?done
    if (isset($_GET["done"])) {
        $result = $uploader->combineChunks("files");
        $size = filesize("files/".$uploader->getUploadName());
        if ($size > $uploader->sizeLimit)
            return array("error" => "Too large");
    }

thanks

**Comment by rnicholus** [comment]
I'd like to keep this open to so I remember to fix this in the repo. If you are able to open up a pull request with the fixes, that would be helpful as well.

You are correct though, you must return a 4xx or 5xx response to the chunking success call to indicate failure.

**Comment by rnicholus** [comment]
I found several other issues in the traditional endpoint code related to file size handling. All fixes are part of 1.0.1.

**Comment by vinitbipinjain** [comment]
Is there anyway I can increase the chunk size to 10 MB?
